### ISSUE TITLE
Show notification when stream status changes

### ISSUE THREAD

**Issue by manniL** [manniL/lichter.io#115]
When the stream status changes, show a little toast that notifies the user

**Comment by Petsamuel** [comment]
i would like to work on this

**Comment by manniL** [comment]
@Petsamuel Sure!

I fetch the stream status here:

https://github.com/manniL/lichter.io/blob/1529e4a51347c16a7e87605d3d7d6e55a585ba71/components/App/Navbar.vue#L15-L20

When it changes from not live -> live, a notification via `useNotification` should be triggered, advertising the stream ☺️

**Comment by kisharnath** [comment]
@manniL I want to work on this issue

**Comment by manniL** [comment]
@kisharnath Go for it 👏
