### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead  

### ISSUE THREAD

**Issue by begueradj** [manniL/lichter.io#27]
Thank you for sharing your work.

I am getting:

>  ERROR  (node:7998) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead  

Whenever I run: `yarn run dev`.

This does not prevent navigating the pages though.
It seems you have to upgrade the webpack version ?

Thank you.

**Comment by manniL** [comment]
Thank you!
Regarding you question, this is a duplicate of https://github.com/nuxt-community/pwa-module/issues/120
