### ISSUE TITLE
Disable/remove mobileAppIOs in config/meta.js (I think?)

### ISSUE THREAD

**Issue by CurtisBelt** [manniL/lichter.io#47]
The Nuxt PWA docs (https://pwa.nuxtjs.org/modules/meta.html#mobileappios) warn about using mobileAppIOs, and references this article: https://medium.com/@firt/dont-use-ios-web-app-meta-tag-irresponsibly-in-your-progressive-web-apps-85d70f4438cb

I don't have an iPhone but it seems like you may fall into this category where it shouldn't be enabled?

**Comment by manniL** [comment]
Thanks for the heads up!

I've added the attribute intentionally as every page has a way to "go back", either via internal linking or via the top menu.

Tested it with my iPhone and it is working as intended ☺️
