### ISSUE TITLE
Make GitHub sponsor link open in new tab

### ISSUE THREAD

**Issue by manniL** [manniL/lichter.io#54]
https://github.com/manniL/lichter.io/blob/acf137ba369b8d53eedb9f638e0a3ae3b8d2ce33/pages/support-me.vue#L174

**Comment by manniL** [comment]
@christopher2007

**Comment by seal62** [comment]
I can do this

**Comment by manniL** [comment]
Already fixed via #55, but thanks! :relaxed:
